name: myenv
channels:
  - conda-forge
dependencies:
  - python=3.11
  - dlib
  - face-recognition
  - numpy
  - opencv
  - pillow
  - click
  - pip
  - streamlit
  - streamlit_webrtc
  - pip:
      - opencv-python-headless
      - protobuf==3.20.*
