channels:
  - conda-forge
dependencies:
  - python=3.9
  - dlib
  - face-recognition
  - numpy
  - opencv
  - pillow
  - click
  - pip
  - streamlit
  - streamlit_webrtc
  - opencv-python-headless
