name: my_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - dlib=19.24.2
  - face-recognition=1.3.0
  - numpy=1.23.5
  - opencv=4.5.5
  - cmake=3.22.2
  - pillow=9.0.0
  - click=8.0.3
  - pip
  - pip:
      - opencv-python
