name: my_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - dlib
  - face-recognition
  - numpy
  - cmake
  - pillow
  - click
  - pip
  - pip:
      - opencv-python  # Installs cv2 separately
