name: myenv
channels:
  - conda-forge
dependencies:
  - python=3.9
  - dlib
  - face-recognition
  - numpy
  - opencv
  - cmake
  - pillow
  - click
  - pip
  - pip:
      - opencv-python-headless
